[package]
name = "wsl-gpg-relay"
version = "0.1.0"
edition = "2021"

[dependencies]
atoi = "2.0.0"
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread", "rt", "io-util", "net", "io-std"] }
